# Generated by Django 6.0 on 2026-03-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DR', 'Driver'), ('PS', 'Passenger'), ('AD', 'Admin')], default='PS', max_length=2),
        ),
    ]
