# Generated by Django 6.0 on 2026-03-23 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='driver_confirmed_boarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='driver_confirming_dropped_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='passenger_boarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='passenger_confirming_dropped_off',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_recieved', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.trip')),
            ],
            options={
                'unique_together': {('reviewer', 'trip')},
            },
        ),
    ]
