# Generated by Django 6.0 on 2026-03-23 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='driver_confirmed_boarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='driver_confirming_dropped_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='passenger_boarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='passenger_confirming_dropped_off',
            field=models.BooleanField(default=False),
        ),
        
    ]
